couchbase:
  nodes:
    - "127.0.0.1"
  bucket:
    name: ""
    password: ""
  bulk-limit: 500
app-ids: []
from-datetime: [2015,1,1,0,0]
to-datetime: [2015,12,1,0,0]
# elastic.node.ip:

# A directory path to export data from Couchbase
# dir.export: /path/to/export